# Use an official Python runtime as a parent image
FROM python:bookworm

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir fastapi uvicorn python-multipart numpy Pillow face_recognition asyncpg uuid requests



